In [3]:
import math

import numpy as np

In [4]:
data = np.random.uniform(-100, 100, size=1000)
np.save("f1.npy", data)

In [7]:
test_func_bound = {
    1:[-100, 100],
    2:[-100, 100],
    3:[-100, 100],
    4:[-5, 5],
    5:[-600, 600],
    6:[-32, 32],
    7:[0, 0],
}

for i in range(1, 7):
    bound = test_func_bound[i]
    data = np.random.uniform(bound[0], bound[1], size=1000)
    np.save("f%d.npy" % i, data)

In [5]:
l1 = np.array([1, 1, 1, 1, 1])
l2 = np.array([2, 2, 2, 2, 2])
l3 = np.array([3, 3, 3, 3, 3])

mean_list = np.array([l1, l2, l3])
# for i, mi in enumerate(mean_list):
#     print(i, mi)


array([[1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3]])

In [6]:
rank = [1, 2, 3, 4, 5]
mu = 7
util_ = np.maximum(0, np.log(mu / 2 + 1) - np.log(rank))
utility = (util_ / (util_.sum())) - (1 / mu)

In [8]:
util_

array([1.5040774 , 0.81093022, 0.40546511, 0.11778304, 0.        ])

In [9]:
utility

array([ 3.87073042e-01,  1.42857143e-01, -2.77555756e-17, -1.01358756e-01,
       -1.42857143e-01])

In [10]:
def calUtility(rewards):
    rank = [0 for i in range(len(rewards))]
    for r, i in enumerate(np.argsort(rewards)[::-1]):
        rank[i] = r + 1  # rank kid by reward
    mu = 7
    util_ = np.maximum(0, np.log(mu / 2 + 1) - np.log(rank))
    utility = (util_ / (util_.sum())) - (1 / mu)
    return utility

In [12]:
r = [3, 1, 6, 7, 8]
for r_, i in enumerate(np.argsort(r)[::-1]):
    print(r_, i)

0 4
1 3
2 2
3 0
4 1


In [2]:
import numpy as np
dg = [1, 2, 3, 1, 1, 2, 2, 3, 3, 3]
sigma = np.diag(dg)

In [86]:
sigma

array([[1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 2, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 3, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 2, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 2, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 3, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 3, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 3]])

In [3]:

def inverse(mat):
    """ Inverse for a diagonal matrix.
      
    mat: An diagonal matrix
    """
    d = mat.shape[0]
    indices = np.diag_indices(d)
    return np.diag(1 / mat[indices])

In [88]:
print(inverse(sigma))

[[1.         0.         0.         0.         0.         0.
  0.         0.         0.         0.        ]
 [0.         0.5        0.         0.         0.         0.
  0.         0.         0.         0.        ]
 [0.         0.         0.33333333 0.         0.         0.
  0.         0.         0.         0.        ]
 [0.         0.         0.         1.         0.         0.
  0.         0.         0.         0.        ]
 [0.         0.         0.         0.         1.         0.
  0.         0.         0.         0.        ]
 [0.         0.         0.         0.         0.         0.5
  0.         0.         0.         0.        ]
 [0.         0.         0.         0.         0.         0.
  0.5        0.         0.         0.        ]
 [0.         0.         0.         0.         0.         0.
  0.         0.33333333 0.         0.        ]
 [0.         0.         0.         0.         0.         0.
  0.         0.         0.33333333 0.        ]
 [0.         0.         0.         0

In [4]:
rg = np.random.default_rng(66666)
mean = [1, 2, 3, 4]
sigma = np.diag([8, 4, 2, 1])
sigma_inv = inverse(sigma)
x_train = rg.multivariate_normal(mean, sigma, 5)

ret1 = np.zeros_like(sigma, dtype=float)
for x in x_train:
    y = (x - mean).reshape(4, 1)
    # ret1 += np.dot(np.dot(np.dot(sigma_inv, y), y.T), sigma_inv)
    ret1 += sigma_inv * y * y.T * sigma_inv
ret1 /= x_train.shape[0]

ret2 = np.zeros_like(sigma, dtype=float)
tmp = np.zeros_like(sigma, dtype=float)
for x in x_train:
    y = (x - mean).reshape(4, 1)
    tmp += y * y.T
ret2 = sigma_inv * tmp * sigma_inv
ret2 /= x_train.shape[0]

ret3 = np.zeros_like(sigma, dtype=float)
diag = np.diag(sigma_inv)
for x in x_train:
    y = (x - mean) * diag
    ret3 += np.diag(y * y)
ret3 /= x_train.shape[0]
print(ret1)
print(ret2)
print(ret3)




[[0.25973295 0.         0.         0.        ]
 [0.         0.07056496 0.         0.        ]
 [0.         0.         0.79446869 0.        ]
 [0.         0.         0.         1.26524775]]
[[ 0.25973295  0.          0.          0.        ]
 [ 0.          0.07056496 -0.         -0.        ]
 [ 0.         -0.          0.79446869 -0.        ]
 [ 0.         -0.         -0.          1.26524775]]
[[0.25973295 0.         0.         0.        ]
 [0.         0.07056496 0.         0.        ]
 [0.         0.         0.79446869 0.        ]
 [0.         0.         0.         1.26524775]]


In [12]:
print(np.diag(sigma))

array([[ 3.85010831,  0.        ,  0.        ,  0.        ],
       [ 0.        , 14.1713403 ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  1.25870284,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.79035904]])

In [115]:
t1 = np.array([2, 3, 4, 5])
print(1 / t1)

[0.5        0.33333333 0.25       0.2       ]


In [13]:
import numpy as np
rg = np.random.default_rng(66666)
d = 7
mu = 5
# mean = np.random.randint(1, 100, size=d)
# sigma = np.random.randint(1, 100, size=d)
mean = np.ones(d)
sigma = np.ones(d)
sigma_inv = 1 / sigma
# x_train = rg.multivariate_normal(mean, np.diag(sigma), mu)
x_train = np.random.rand(mu, d)
f = np.random.randint(1, 100, size=mu)



In [16]:
x_train

array([[0.07726816, 0.64824261, 0.34204371, 0.18246443, 0.29859897,
        0.8880455 , 0.84447806],
       [0.57367185, 0.26634243, 0.82498753, 0.18933588, 0.26672184,
        0.31281133, 0.89788844],
       [0.0720262 , 0.08797784, 0.59655564, 0.64179357, 0.33381629,
        0.28710383, 0.02938456],
       [0.49972444, 0.37976091, 0.05291851, 0.076592  , 0.10414954,
        0.65947679, 0.35111669],
       [0.84851183, 0.59155188, 0.52814652, 0.07826432, 0.74341434,
        0.39889907, 0.9020331 ]])

In [18]:
Y = x_train - mean

In [15]:
import time

start = time.time()
ans1 = np.zeros_like(mean, dtype=float)
for i in range(mu):
    ans1 += sigma_inv * (x_train[i] - mean) * f[i]
ans1 /= mu
end = time.time()
print(str(end - start))
# ans2 = np.zeros_like(mean, dtype=float)

start = time.time()
ans2 = sigma_inv * np.dot((x_train - mean).T, f) / mu
# ans2 = (sigma_inv * np.dot(f.reshape(1, mu), (x_train - mean)).flatten()) / mu
end = time.time()
print(str(end - start))
print(sum(ans1 - ans2))
print(ans1)
print(ans2)


0.0001742839813232422
7.891654968261719e-05
3.552713678800501e-15
[-22.82337662 -31.27774434 -20.18607299 -39.94379445 -29.6517156
 -29.8751217  -13.75936615]
[-22.82337662 -31.27774434 -20.18607299 -39.94379445 -29.6517156
 -29.8751217  -13.75936615]


In [6]:
np.dot(f.reshape(1, 10), (x_train - mean)).flatten().shape

ValueError: cannot reshape array of size 10000 into shape (1,10)

In [42]:
a = Y[0][:5]
sig = np.array([1, 2, 3, 4, 5])
a * a * sig * sig

array([ 0.85143405,  0.49493304,  3.89615829, 10.6938306 , 12.29908518])

In [39]:
a

array([-0.92273184, -0.35175739, -0.65795629, -0.81753557, -0.70140103])

In [1]:
import time
time.time()

1700293557.171977

In [1]:
import numpy as np
rewards = np.array([500, 300, 700, 900, 100, 400])
ranks = np.zeros_like(rewards)
for r, idx in enumerate(np.argsort(rewards)):
    ranks[idx] = r + 1

print(ranks)

[4 2 5 6 1 3]


In [11]:
import math
math.log(7)

1.9459101490553132

In [14]:
math.e ** 1.94

6.958750970637271

In [15]:
max(0., 3.7)

3.7

In [23]:
def u(rewards):
    ranks = np.zeros_like(rewards)
    for r, idx in enumerate(np.argsort(rewards)[::-1]):
        ranks[idx] = r + 1

    mu = rewards.shape[0]
    dividend = np.maximum(0., np.log(mu / 2 + 1) - np.log(ranks))
    divisor = dividend.sum()
    utils = dividend / divisor
    utils -= 1 / mu
    return utils

In [25]:
rewards = np.array([500, 300, 700, 900, 100, 400])
print(u(rewards))

[-0.04513433 -0.16666667  0.12615589  0.41897844 -0.16666667 -0.16666667]


In [21]:
def calUtility(rewards):
    rank = [0 for i in range(len(rewards))]
    for r, i in enumerate(np.argsort(rewards)[::-1]):
        rank[i] = r + 1  # rank kid by reward
    mu = rewards.shape[0]
    util_ = np.maximum(0, np.log(mu / 2 + 1) - np.log(rank))
    utility = (util_ / (util_.sum())) - (1 / mu)
    return utility

In [22]:
print(calUtility(rewards))

[-0.04513433 -0.16666667  0.12615589  0.41897844 -0.16666667 -0.16666667]


In [9]:
x = np.ones(3)
x[1] = 2
c = np.outer(x, x)
c

array([[1., 2., 1.],
       [2., 4., 2.],
       [1., 2., 1.]])

In [1]:
import numpy as np

In [2]:
diag = np.array([1, 2, 3, 4, 5])
cov = np.diag(diag)
cov

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [3]:
evals, evecs = np.linalg.eig(cov)

In [4]:
evals

array([1., 2., 3., 4., 5.])

In [5]:
evecs

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [6]:
evals ** 0.5

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798])

In [34]:
def gen_children(m)

def decompose(mat):
    evals, evecs = np.linalg.eig(mat)
    C = evecs @ (np.diag(evals ** 0.5))
    return C.T

def calDelta(mat):
    d = mat.shape[0]
    return np.power(abs(np.linalg.det(mat)), 1 / d)

def fit()

In [25]:
A = decompose(np.mat("6, -3, 1; -3, 2, 0; 1, 0, 4"))

In [35]:
calDelta(A)

1.4677992676220704

matrix([[ 2.41856456, -1.24858383,  0.6346042 ],
        [-0.27754941, -0.49916794,  0.07566629],
        [-0.27113055,  0.43802945,  1.89513908]])

In [22]:
B.T @ B

matrix([[ 6.00000000e+00, -3.00000000e+00,  1.00000000e+00],
        [-3.00000000e+00,  2.00000000e+00, -4.86769505e-16],
        [ 1.00000000e+00, -4.86769505e-16,  4.00000000e+00]])

In [36]:
x = np.array([[1,2,3],[4,5,6]])

In [37]:
len(x)

2

In [38]:
len(x[0])

3